In [ ]:
# The MNIST dataset is present in Keras, so we dont need to mount the drive
import keras

In [ ]:
from keras.datasets import mnist
from keras.utils import np_utils

(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [ ]:
train_images.shape
# (60000, 28, 28)
# 60,000 images with each image size being 28 * 28 pixels

(60000, 28, 28)

In [ ]:
train_images[0].shape

(28, 28)

In [ ]:
train_images[11] #28 rows and 28 columns

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [ ]:
train_images = train_images.reshape((60000, 28, 28, 1)) # we are adding depth here, since numbers are grayscale images, depth will be 1. If it is colored image then depth will be 3.

In [ ]:
# now we need to perform feature scaling, as the pixel values are ranging from 0 to 255. we need to bring them down to the range [0,1].
# In deep learning projects most of the times we use min/max scaling, i.e., normalization.
# min = 0, max = 255 
# scaling = x - min/(max - min)
# scaling = x - 0/(255 - 0)  ----> this is nothing but just dividing the x by 255. so we divide every pixel by 255 to do the scaling.

train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255

In [ ]:
# here we have 10 categories in the target variable as we have 10 digits from 0 to 9. Now we need to convert this to one hot encoded columns.
# after encoding we will have 10 new columns added to the labels data.
train_labels = np_utils.to_categorical(train_labels)
test_labels = np_utils.to_categorical(test_labels)

In [ ]:
train_labels.shape

(60000, 10)

In [ ]:
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [ ]:
from keras import layers
from keras import models

model = models.Sequential()

# adding first convolution layer with 32 nodes--> 32 filters, with size of each filter being 3*3. 
# while adding first convolution layer, it also adds input layer 
# input image size is 28 * 28 * 1
model.add(layers.Conv2D(32, (3,3), activation ='relu', input_shape=(28,28,1)))

# adding max pooling layer, with window size 2*2. i.e., within each 2*2 window on convolved image we find the max value.
model.add(layers.MaxPooling2D((2,2)))

# 2nd convolution layer with 16 filters with size 5*5
model.add(layers.Conv2D(16, (5,5) , activation='relu'))

# 2nd max pooling layer
model.add(layers.MaxPooling2D((2,2)))

In [ ]:
# Now after the CNN layers, we flatten the final matrix, and feed it to ANN for classification.
# after flattening we pass it to  dense hidden layers and finally to output layer

model.add(layers.Flatten())

# first dense hidden layer
# 64 nodes --> some math has to be done to know what will be the size of the flattened array, with activation function as relu
model.add(layers.Dense(64, activation = 'relu'))

# output layer with 10 nodes as we have 10 digits as categories.
model.add(layers.Dense(10, activation = 'softmax'))

In [ ]:
model.compile(optimizer = 'rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(train_images,train_labels,epochs=10,batch_size=64 )

Epoch 1/10
938/938 [==============================] - 9s 9ms/step - loss: 0.2239 - accuracy: 0.9327
Epoch 2/10
938/938 [==============================] - 11s 11ms/step - loss: 0.0692 - accuracy: 0.9789
Epoch 3/10
938/938 [==============================] - 8s 8ms/step - loss: 0.0484 - accuracy: 0.9852
Epoch 4/10
938/938 [==============================] - 7s 7ms/step - loss: 0.0379 - accuracy: 0.9883
Epoch 5/10
938/938 [==============================] - 7s 7ms/step - loss: 0.0322 - accuracy: 0.9897
Epoch 6/10
938/938 [==============================] - 7s 7ms/step - loss: 0.0262 - accuracy: 0.9916
Epoch 7/10
938/938 [==============================] - 9s 9ms/step - loss: 0.0229 - accuracy: 0.9930
Epoch 8/10
938/938 [==============================] - 7s 8ms/step - loss: 0.0190 - accuracy: 0.9940
Epoch 9/10
938/938 [==============================] - 7s 7ms/step - loss: 0.0177 - accuracy: 0.9949
Epoch 10/10
938/938 [==============================] - 7s 7ms/step - loss: 0.0144 - accuracy: 0.99

In [ ]:
test_loss, test_acc = model.evaluate(test_images,test_labels)

313/313 [==============================] - 1s 4ms/step - loss: 0.0364 - accuracy: 0.9889


In [ ]:
test_images[0].shape

(28, 28, 1)

In [ ]:
model.layers

In [ ]:
test_data = train_images[10].reshape(1,28,28,1) # taking single image from train data and reshaping it

In [ ]:
import numpy as np
predictions = model.predict(test_images)
predictions = np.argmax(predictions, axis =1)

In [ ]:
predictions

array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(np.argmax(test_labels,axis = 1),predictions)

In [ ]:
cm # 10*10 matrix as we have 10 categories
# all the values in diagonal are number of correctly predicted values and rest of them are incorrectly predicted values

array([[ 977,    0,    1,    0,    0,    0,    1,    0,    1,    0],
       [   0, 1132,    0,    1,    0,    0,    1,    0,    0,    1],
       [   2,    2, 1022,    1,    2,    0,    0,    2,    1,    0],
       [   0,    0,    1, 1004,    0,    3,    0,    1,    1,    0],
       [   0,    0,    2,    0,  975,    0,    3,    0,    1,    1],
       [   2,    0,    0,    7,    0,  878,    3,    1,    0,    1],
       [   3,    2,    0,    1,    1,    1,  950,    0,    0,    0],
       [   0,    6,    4,    2,    0,    0,    0, 1015,    0,    1],
       [   5,    0,    2,    1,    1,    2,    2,    1,  960,    0],
       [   4,    0,    0,    4,   10,    8,    1,    3,    3,  976]])

In [ ]:
model.save('models/mnist_CNN.h5')

In [ ]:
from keras.models import load_model
model = load_model('models/mnist_CNN.h5')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
os.chdir('/content/drive/My Drive')

In [ ]:
from PIL import Image
img = Image.open('0.png').convert("L")
img = img.resize((28,28))
img2arr = np.array(img)
img2arr = img2arr.reshape(1,28,28,1)
pred = model.predict(img2arr)

In [ ]:
np.argmax(pred,axis=1)

array([0])

In [ ]:
img = Image.open('7.png').convert("L")
img = img.resize((28,28))
img2arr = np.array(img)
img2arr = img2arr.reshape(1,28,28,1)
pred = model.predict(img2arr)
pred = np.argmax(pred,axis=1)
print(pred)

[7]
